### ISSUE TITLE
Maven dependencies folder is not created

### ISSUE THREAD

**Issue by lax-mag** [tabhresh/Edureka_28July#10]
Hi abhresh

I cannot see the maven dependencies folder after adding the plugins and dependencies for selenium and testng.
I can see error(red underline) in xml as shown in the atatchment.
![image](https://user-images.githubusercontent.com/41930890/45036784-0966d400-b07b-11e8-99a4-d8d50a18cf63.png)

Any configuration issue. Please help me out with this issue.

Thanks.

**Comment by bhavsbhatnagar2484** [comment]
Hi Laxmi, 
can u share ur gmail id, we may discuss the issues there?
my id is: bhavs.bhatnagar@gmail.com
