### ISSUE TITLE
Problem with debugging automation for web pages.

### ISSUE THREAD

**Issue by jcox01** [tabhresh/Edureka_28July#4]
When debugging, I receive a "Source not found" error.  The snapshot is below.  (Debugging works fine for any none browser related issues.)
To duplicate, I place a break point into the script this time on a WebDriverWait and WebElement.  Starting debug, the script advances to the break, then if I use F8 it  will continue.  If I use F5, I get the "Source not found" issue.
The script runs fine if not in debug.

The jar file mentioned is in the build path.

Thank you

John

![image](https://user-images.githubusercontent.com/40525229/44305713-880a0480-a34c-11e8-8a89-2f056b8632dd.png)

Indigo.java

**Comment by jcox01** [comment]
Abhresh,

Sorry, I thought it had be pasted here in the blog, but it took only the
name.

Due to a syncing issue in git, I am including the code here in a zip file.

**Comment by tabhresh** [comment]
Use insert code feature here to past the code as i am not getting the code. Share it through support@edureka.co

**Comment by AbhreshSugandhi** [comment]
Didn't received  your code yet
