### ISSUE TITLE
Selenium Grid set-up

### ISSUE THREAD

**Issue by lax-mag** [tabhresh/Edureka_28July#5]
hi abhresh

step 1:
C:\SELENIUM\Jar files\Grid> java -jar  selenium-3.4.0.jar -role hub

Below screen is dispalyed as Selenium Grid is up and running
![image](https://user-images.githubusercontent.com/41930890/44515065-3c09e780-a6df-11e8-844e-4e8d29359bc0.png)

step 2:
java -jar selenium-3.4.0.jar -role node -browser browserName=chrome -browser browserName=firefox -hub http://192.168.1.8:4444/grid/register -port 5566

![image](https://user-images.githubusercontent.com/41930890/44515160-71163a00-a6df-11e8-9312-c6656fe7ab80.png)

the command prompt shows as node is registered to hub and ready to use as in above image 

I have raised a ticket to support team but no response from them.
Please help me out.

Thanks.
Laxmi.

**Comment by tabhresh** [comment]
You didnt mentioned the problem you are facing? Give more details.

**Comment by lax-mag** [comment]
the browsers are not assigned

**Comment by lax-mag** [comment]
whne i run the code the Exception is as below
Exception in thread "main" org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'

**Comment by AbhreshSugandhi** [comment]
suggested to get in touch with the support team!
