### ISSUE TITLE
Package under a Package is not working

### ISSUE THREAD

**Issue by bhavsbhatnagar2484** [tabhresh/Edureka_28July#6]
Hi,

I tried both the methods, and also taken help from this url but nothing is working.
https://coderanch.com/t/486403/ide/Eclipse-add-package

Does someone else has a solution.?
![image](https://user-images.githubusercontent.com/41821253/44615231-e8200f80-a852-11e8-9cc0-b3b8a80a3526.png)

![image](https://user-images.githubusercontent.com/41821253/44615236-f40bd180-a852-11e8-8fdc-d62cbcfcb043.png)

**Comment by bhavsbhatnagar2484** [comment]
Ok, i finally got the solution for this.
I am working here in Package Explorer, u need to change it to Navigator where we can see the hierarchical structure of packages n folders.

to change the package explorer to Navigator,
Window->Show View->Navigator
By doing this you will able to see packages as parent child hierarchy.
![image](https://user-images.githubusercontent.com/41821253/44618905-72409600-a89c-11e8-950d-0869ec45e954.png)

**Comment by lax-mag** [comment]
cool. its working for me also now.
Thanks bhavya.
