### ISSUE TITLE
Keyword Driven Frame Work error

### ISSUE THREAD

**Issue by lax-mag** [tabhresh/Edureka_28July#7]
Error is displayed as below after running the keyword driven example the file under 
module10 ->execution.java.

Starting ChromeDriver 2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e) on port 29366
Only local connections are allowed.
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Aug 29, 2018 6:57:17 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS

**Comment by AbhreshSugandhi** [comment]
If i am not wrong we have cleared this issue during the session!
